//
//  Variables.swift
//  Virtual_Instrument
//
//  Created by Sean on 8/16/19.
//  Copyright © 2019 Sean. All rights reserved.
//

import Foundation
import CoreMIDI

class vari{

    //Note Arrays
    let cArray:[Float] = [32.70, 65.41, 130.81, 261.63, 523.25, 1046.50] //24, 36, 48, 60, 72, 84 --> corresponding MIDI values
    let csArray:[Float] = [34.65, 69.30, 138.59, 277.18, 554.37] //25, 37, 49, 61, 73, 85
    let dArray:[Float] = [36.71, 73.42, 146.83, 293.66, 587.33] //26, 38, 50, 62, 74, 86
    let efArray:[Float] = [38.89, 77.78, 155.56, 311.13, 622.25] //27, 39, 51, 63, 75, 87
    let eArray:[Float] = [41.20, 82.41, 164.81, 329.63, 659.25] //28, 40, 52, 64, 76, 88
    let fArray:[Float] = [43.65, 87.31, 174.61, 349.23, 698.46] //29, 41, 53, 65, 77, 89
    let fsArray:[Float] = [46.25, 92.5, 185, 369.99, 739.99] //30, 42, 54, 66, 78, 90
    let gArray:[Float] = [49.00, 98.0, 196, 392, 783.99] //31, 43, 55, 67, 79, 91
    let gsArray:[Float] = [51.91, 103.83, 207.65, 415.3, 830.61] //32, 44, 56, 68, 80, 92
    let aArray:[Float] = [55.00, 110, 220, 440, 880] //33, 45, 57, 69, 81, 93
    let asArray:[Float] = [58.27, 116.54, 233.08, 466.16, 932.33] //34, 46, 58, 70, 82, 94
    let bArray:[Float] = [61.47, 123.47, 246.94, 493.88, 987.77] //35, 47, 59, 71, 83, 95
    
    let C = [NSHomeDirectory() + "/Desktop/Virtual_Instrument/AudioFiles/C1.wav", NSHomeDirectory() + "/Desktop/Virtual_Instrument/AudioFiles/C2.wav", NSHomeDirectory() + "/Desktop/Virtual_Instrument/AudioFiles/C3.wav", NSHomeDirectory() + "/Desktop/Virtual_Instrument/AudioFiles/C4.wav", NSHomeDirectory() + "/Desktop/Virtual_Instrument/AudioFiles/C5.wav", NSHomeDirectory() + "/Desktop/Virtual_Instrument/AudioFiles/C1 - Strings.wav", NSHomeDirectory() + "/Desktop/Virtual_Instrument/AudioFiles/C2 - Strings.wav", NSHomeDirectory() + "/Desktop/Virtual_Instrument/AudioFiles/C3 - Strings.wav", NSHomeDirectory() + "/Desktop/Virtual_Instrument/AudioFiles/C4 - Strings.wav", NSHomeDirectory() + "/Desktop/Virtual_Instrument/AudioFiles/C5 - Strings.wav", NSHomeDirectory() + "/Desktop/Virtual_Instrument/AudioFiles/C1 - Horns.wav", NSHomeDirectory() + "/Desktop/Virtual_Instrument/AudioFiles/C2 - Horns.wav", NSHomeDirectory() + "/Desktop/Virtual_Instrument/AudioFiles/C3 - Horns.wav", NSHomeDirectory() + "/Desktop/Virtual_Instrument/AudioFiles/C4 - Horns.wav", NSHomeDirectory() + "/Desktop/Virtual_Instrument/AudioFiles/C5 - Horns.wav", NSHomeDirectory() + "/Desktop/Virtual_Instrument/AudioFiles/C1 - Synth1.wav", NSHomeDirectory() + "/Desktop/Virtual_Instrument/AudioFiles/C2 - Synth1.wav", NSHomeDirectory() + "/Desktop/Virtual_Instrument/AudioFiles/C3 - Synth1.wav", NSHomeDirectory() + "/Desktop/Virtual_Instrument/AudioFiles/C4 - Synth1.wav", NSHomeDirectory() + "/Desktop/Virtual_Instrument/AudioFiles/C5 - Synth1.wav", NSHomeDirectory() + "/Desktop/Virtual_Instrument/AudioFiles/C1 - Synth2.wav", NSHomeDirectory() + "/Desktop/Virtual_Instrument/AudioFiles/C2 - Synth2.wav", NSHomeDirectory() + "/Desktop/Virtual_Instrument/AudioFiles/C3 - Synth2.wav", NSHomeDirectory() + "/Desktop/Virtual_Instrument/AudioFiles/C4 - Synth2.wav", NSHomeDirectory() + "/Desktop/Virtual_Instrument/AudioFiles/C5 - Synth2.wav", NSHomeDirectory() + "/Desktop/Virtual_Instrument/AudioFiles/C1 - Pad1.wav", NSHomeDirectory() + "/Desktop/Virtual_Instrument/AudioFiles/C2 - Pad1.wav", NSHomeDirectory() + "/Desktop/Virtual_Instrument/AudioFiles/C3 - Pad1.wav", NSHomeDirectory() + "/Desktop/Virtual_Instrument/AudioFiles/C4 - Pad1.wav", NSHomeDirectory() + "/Desktop/Virtual_Instrument/AudioFiles/C5 - Pad1.wav", NSHomeDirectory() + "/Desktop/Virtual_Instrument/AudioFiles/C1 - Pad2.wav", NSHomeDirectory() + "/Desktop/Virtual_Instrument/AudioFiles/C2 - Pad2.wav", NSHomeDirectory() + "/Desktop/Virtual_Instrument/AudioFiles/C3 - Pad2.wav", NSHomeDirectory() + "/Desktop/Virtual_Instrument/AudioFiles/C4 - Pad2.wav", NSHomeDirectory() + "/Desktop/Virtual_Instrument/AudioFiles/C5 - Pad2.wav"]
    
    let Db = [NSHomeDirectory() + "/Desktop/Virtual_Instrument/AudioFiles/Db1.wav", NSHomeDirectory() + "/Desktop/Virtual_Instrument/AudioFiles/Db2.wav", NSHomeDirectory() + "/Desktop/Virtual_Instrument/AudioFiles/Db3.wav", NSHomeDirectory() + "/Desktop/Virtual_Instrument/AudioFiles/Db4.wav", NSHomeDirectory() + "/Desktop/Virtual_Instrument/AudioFiles/C#1 - Strings.wav", NSHomeDirectory() + "/Desktop/Virtual_Instrument/AudioFiles/C#2 - Strings.wav", NSHomeDirectory() + "/Desktop/Virtual_Instrument/AudioFiles/C#3 - Strings.wav", NSHomeDirectory() + "/Desktop/Virtual_Instrument/AudioFiles/C#4 - Strings.wav", NSHomeDirectory() + "/Desktop/Virtual_Instrument/AudioFiles/C#1 - Horns.wav", NSHomeDirectory() + "/Desktop/Virtual_Instrument/AudioFiles/C#2 - Horns.wav", NSHomeDirectory() + "/Desktop/Virtual_Instrument/AudioFiles/C#3 - Horns.wav", NSHomeDirectory() + "/Desktop/Virtual_Instrument/AudioFiles/C#4 - Horns.wav", NSHomeDirectory() + "/Desktop/Virtual_Instrument/AudioFiles/C#1 - Synth1.wav", NSHomeDirectory() + "/Desktop/Virtual_Instrument/AudioFiles/C#2 - Synth1.wav", NSHomeDirectory() + "/Desktop/Virtual_Instrument/AudioFiles/C#3 - Synth1.wav", NSHomeDirectory() + "/Desktop/Virtual_Instrument/AudioFiles/C#4 - Synth1.wav", NSHomeDirectory() + "/Desktop/Virtual_Instrument/AudioFiles/C#1 - Synth2.wav", NSHomeDirectory() + "/Desktop/Virtual_Instrument/AudioFiles/C#2 - Synth2.wav", NSHomeDirectory() + "/Desktop/Virtual_Instrument/AudioFiles/C#3 - Synth2.wav", NSHomeDirectory() + "/Desktop/Virtual_Instrument/AudioFiles/C#4 - Synth2.wav", NSHomeDirectory() + "/Desktop/Virtual_Instrument/AudioFiles/C#1 - Pad1.wav", NSHomeDirectory() + "/Desktop/Virtual_Instrument/AudioFiles/C#2 - Pad1.wav", NSHomeDirectory() + "/Desktop/Virtual_Instrument/AudioFiles/C#3 - Pad1.wav", NSHomeDirectory() + "/Desktop/Virtual_Instrument/AudioFiles/C#4 - Pad1.wav", NSHomeDirectory() + "/Desktop/Virtual_Instrument/AudioFiles/C#1 - Pad2.wav", NSHomeDirectory() + "/Desktop/Virtual_Instrument/AudioFiles/C#2 - Pad2.wav", NSHomeDirectory() + "/Desktop/Virtual_Instrument/AudioFiles/C#3 - Pad2.wav", NSHomeDirectory() + "/Desktop/Virtual_Instrument/AudioFiles/C#4 - Pad2.wav"]
    
    let D = [NSHomeDirectory() + "/Desktop/Virtual_Instrument/AudioFiles/D1.wav", NSHomeDirectory() + "/Desktop/Virtual_Instrument/AudioFiles/D2.wav", NSHomeDirectory() + "/Desktop/Virtual_Instrument/AudioFiles/D3.wav", NSHomeDirectory() + "/Desktop/Virtual_Instrument/AudioFiles/D4.wav", NSHomeDirectory() + "/Desktop/Virtual_Instrument/AudioFiles/D1 - Strings.wav", NSHomeDirectory() + "/Desktop/Virtual_Instrument/AudioFiles/D2 - Strings.wav", NSHomeDirectory() + "/Desktop/Virtual_Instrument/AudioFiles/D3 - Strings.wav", NSHomeDirectory() + "/Desktop/Virtual_Instrument/AudioFiles/D4 - Strings.wav", NSHomeDirectory() + "/Desktop/Virtual_Instrument/AudioFiles/D1 - Horns.wav", NSHomeDirectory() + "/Desktop/Virtual_Instrument/AudioFiles/D2 - Horns.wav", NSHomeDirectory() + "/Desktop/Virtual_Instrument/AudioFiles/D3 - Horns.wav", NSHomeDirectory() + "/Desktop/Virtual_Instrument/AudioFiles/D4 - Horns.wav", NSHomeDirectory() + "/Desktop/Virtual_Instrument/AudioFiles/D1 - Synth1.wav", NSHomeDirectory() + "/Desktop/Virtual_Instrument/AudioFiles/D2 - Synth1.wav", NSHomeDirectory() + "/Desktop/Virtual_Instrument/AudioFiles/D3 - Synth1.wav", NSHomeDirectory() + "/Desktop/Virtual_Instrument/AudioFiles/D4 - Synth1.wav", NSHomeDirectory() + "/Desktop/Virtual_Instrument/AudioFiles/D1 - Synth2.wav", NSHomeDirectory() + "/Desktop/Virtual_Instrument/AudioFiles/D2 - Synth2.wav", NSHomeDirectory() + "/Desktop/Virtual_Instrument/AudioFiles/D3 - Synth2.wav", NSHomeDirectory() + "/Desktop/Virtual_Instrument/AudioFiles/D4 - Synth2.wav", NSHomeDirectory() + "/Desktop/Virtual_Instrument/AudioFiles/D1 - Pad1.wav", NSHomeDirectory() + "/Desktop/Virtual_Instrument/AudioFiles/D2 - Pad1.wav", NSHomeDirectory() + "/Desktop/Virtual_Instrument/AudioFiles/D3 - Pad1.wav", NSHomeDirectory() + "/Desktop/Virtual_Instrument/AudioFiles/D4 - Pad1.wav", NSHomeDirectory() + "/Desktop/Virtual_Instrument/AudioFiles/D1 - Pad2.wav", NSHomeDirectory() + "/Desktop/Virtual_Instrument/AudioFiles/D2 - Pad2.wav", NSHomeDirectory() + "/Desktop/Virtual_Instrument/AudioFiles/D3 - Pad2.wav", NSHomeDirectory() + "/Desktop/Virtual_Instrument/AudioFiles/D4 - Pad2.wav"]
    
    let Eb = [NSHomeDirectory() + "/Desktop/Virtual_Instrument/AudioFiles/Eb1.wav", NSHomeDirectory() + "/Desktop/Virtual_Instrument/AudioFiles/Eb2.wav", NSHomeDirectory() + "/Desktop/Virtual_Instrument/AudioFiles/Eb3.wav", NSHomeDirectory() + "/Desktop/Virtual_Instrument/AudioFiles/Eb4.wav", NSHomeDirectory() + "/Desktop/Virtual_Instrument/AudioFiles/D#1 - Strings.wav", NSHomeDirectory() + "/Desktop/Virtual_Instrument/AudioFiles/D#2 - Strings.wav", NSHomeDirectory() + "/Desktop/Virtual_Instrument/AudioFiles/D#3 - Strings.wav", NSHomeDirectory() + "/Desktop/Virtual_Instrument/AudioFiles/D#4 - Strings.wav", NSHomeDirectory() + "/Desktop/Virtual_Instrument/AudioFiles/D#1 - Horns.wav", NSHomeDirectory() + "/Desktop/Virtual_Instrument/AudioFiles/D#2 - Horns.wav", NSHomeDirectory() + "/Desktop/Virtual_Instrument/AudioFiles/D#3 - Horns.wav", NSHomeDirectory() + "/Desktop/Virtual_Instrument/AudioFiles/D#4 - Horns.wav", NSHomeDirectory() + "/Desktop/Virtual_Instrument/AudioFiles/D#1 - Synth1.wav", NSHomeDirectory() + "/Desktop/Virtual_Instrument/AudioFiles/D#2 - Synth1.wav", NSHomeDirectory() + "/Desktop/Virtual_Instrument/AudioFiles/D#3 - Synth1.wav", NSHomeDirectory() + "/Desktop/Virtual_Instrument/AudioFiles/D#4 - Synth1.wav", NSHomeDirectory() + "/Desktop/Virtual_Instrument/AudioFiles/D#1 - Synth2.wav", NSHomeDirectory() + "/Desktop/Virtual_Instrument/AudioFiles/D#2 - Synth2.wav", NSHomeDirectory() + "/Desktop/Virtual_Instrument/AudioFiles/D#3 - Synth2.wav", NSHomeDirectory() + "/Desktop/Virtual_Instrument/AudioFiles/D#4 - Synth2.wav", NSHomeDirectory() + "/Desktop/Virtual_Instrument/AudioFiles/D#1 - Pad1.wav", NSHomeDirectory() + "/Desktop/Virtual_Instrument/AudioFiles/D#2 - Pad1.wav", NSHomeDirectory() + "/Desktop/Virtual_Instrument/AudioFiles/D#3 - Pad1.wav", NSHomeDirectory() + "/Desktop/Virtual_Instrument/AudioFiles/D#4 - Pad1.wav", NSHomeDirectory() + "/Desktop/Virtual_Instrument/AudioFiles/D#1 - Pad2.wav", NSHomeDirectory() + "/Desktop/Virtual_Instrument/AudioFiles/D#2 - Pad2.wav", NSHomeDirectory() + "/Desktop/Virtual_Instrument/AudioFiles/D#3 - Pad2.wav", NSHomeDirectory() + "/Desktop/Virtual_Instrument/AudioFiles/D#4 - Pad2.wav"]
    
    let E = [NSHomeDirectory() + "/Desktop/Virtual_Instrument/AudioFiles/E1.wav", NSHomeDirectory() + "/Desktop/Virtual_Instrument/AudioFiles/E2.wav", NSHomeDirectory() + "/Desktop/Virtual_Instrument/AudioFiles/E3.wav", NSHomeDirectory() + "/Desktop/Virtual_Instrument/AudioFiles/E4.wav", NSHomeDirectory() + "/Desktop/Virtual_Instrument/AudioFiles/E1 - Strings.wav", NSHomeDirectory() + "/Desktop/Virtual_Instrument/AudioFiles/E2 - Strings.wav", NSHomeDirectory() + "/Desktop/Virtual_Instrument/AudioFiles/E3 - Strings.wav", NSHomeDirectory() + "/Desktop/Virtual_Instrument/AudioFiles/E4 - Strings.wav", NSHomeDirectory() + "/Desktop/Virtual_Instrument/AudioFiles/E1 - Horns.wav", NSHomeDirectory() + "/Desktop/Virtual_Instrument/AudioFiles/E2 - Horns.wav", NSHomeDirectory() + "/Desktop/Virtual_Instrument/AudioFiles/E3 - Horns.wav", NSHomeDirectory() + "/Desktop/Virtual_Instrument/AudioFiles/E4 - Horns.wav", NSHomeDirectory() + "/Desktop/Virtual_Instrument/AudioFiles/E1 - Synth1.wav", NSHomeDirectory() + "/Desktop/Virtual_Instrument/AudioFiles/E2 - Synth1.wav", NSHomeDirectory() + "/Desktop/Virtual_Instrument/AudioFiles/E3 - Synth1.wav", NSHomeDirectory() + "/Desktop/Virtual_Instrument/AudioFiles/E4 - Synth1.wav", NSHomeDirectory() + "/Desktop/Virtual_Instrument/AudioFiles/E1 - Synth2.wav", NSHomeDirectory() + "/Desktop/Virtual_Instrument/AudioFiles/E2 - Synth2.wav", NSHomeDirectory() + "/Desktop/Virtual_Instrument/AudioFiles/E3 - Synth2.wav", NSHomeDirectory() + "/Desktop/Virtual_Instrument/AudioFiles/E4 - Synth2.wav", NSHomeDirectory() + "/Desktop/Virtual_Instrument/AudioFiles/E1 - Pad1.wav", NSHomeDirectory() + "/Desktop/Virtual_Instrument/AudioFiles/E2 - Pad1.wav", NSHomeDirectory() + "/Desktop/Virtual_Instrument/AudioFiles/E3 - Pad1.wav", NSHomeDirectory() + "/Desktop/Virtual_Instrument/AudioFiles/E4 - Pad1.wav",NSHomeDirectory() + "/Desktop/Virtual_Instrument/AudioFiles/E1 - Pad2.wav", NSHomeDirectory() + "/Desktop/Virtual_Instrument/AudioFiles/E2 - Pad2.wav", NSHomeDirectory() + "/Desktop/Virtual_Instrument/AudioFiles/E3 - Pad2.wav", NSHomeDirectory() + "/Desktop/Virtual_Instrument/AudioFiles/E4 - Pad2.wav"]
    
    let F = [NSHomeDirectory() + "/Desktop/Virtual_Instrument/AudioFiles/F1.wav", NSHomeDirectory() + "/Desktop/Virtual_Instrument/AudioFiles/F2.wav", NSHomeDirectory() + "/Desktop/Virtual_Instrument/AudioFiles/F3.wav", NSHomeDirectory() + "/Desktop/Virtual_Instrument/AudioFiles/F4.wav", NSHomeDirectory() + "/Desktop/Virtual_Instrument/AudioFiles/F1 - Strings.wav", NSHomeDirectory() + "/Desktop/Virtual_Instrument/AudioFiles/F2 - Strings.wav", NSHomeDirectory() + "/Desktop/Virtual_Instrument/AudioFiles/F3 - Strings.wav", NSHomeDirectory() + "/Desktop/Virtual_Instrument/AudioFiles/F4 - Strings.wav", NSHomeDirectory() + "/Desktop/Virtual_Instrument/AudioFiles/F1 - Horns.wav", NSHomeDirectory() + "/Desktop/Virtual_Instrument/AudioFiles/F2 - Horns.wav", NSHomeDirectory() + "/Desktop/Virtual_Instrument/AudioFiles/F3 - Horns.wav", NSHomeDirectory() + "/Desktop/Virtual_Instrument/AudioFiles/F4 - Horns.wav", NSHomeDirectory() + "/Desktop/Virtual_Instrument/AudioFiles/F1 - Synth1.wav", NSHomeDirectory() + "/Desktop/Virtual_Instrument/AudioFiles/F2 - Synth1.wav", NSHomeDirectory() + "/Desktop/Virtual_Instrument/AudioFiles/F3 - Synth1.wav", NSHomeDirectory() + "/Desktop/Virtual_Instrument/AudioFiles/F4 - Synth1.wav", NSHomeDirectory() + "/Desktop/Virtual_Instrument/AudioFiles/F1 - Synth2.wav", NSHomeDirectory() + "/Desktop/Virtual_Instrument/AudioFiles/F2 - Synth2.wav", NSHomeDirectory() + "/Desktop/Virtual_Instrument/AudioFiles/F3 - Synth2.wav", NSHomeDirectory() + "/Desktop/Virtual_Instrument/AudioFiles/F4 - Synth2.wav", NSHomeDirectory() + "/Desktop/Virtual_Instrument/AudioFiles/F1 - Pad1.wav", NSHomeDirectory() + "/Desktop/Virtual_Instrument/AudioFiles/F2 - Pad1.wav", NSHomeDirectory() + "/Desktop/Virtual_Instrument/AudioFiles/F3 - Pad1.wav", NSHomeDirectory() + "/Desktop/Virtual_Instrument/AudioFiles/F4 - Pad1.wav", NSHomeDirectory() + "/Desktop/Virtual_Instrument/AudioFiles/F1 - Pad2.wav", NSHomeDirectory() + "/Desktop/Virtual_Instrument/AudioFiles/F2 - Pad2.wav", NSHomeDirectory() + "/Desktop/Virtual_Instrument/AudioFiles/F3 - Pad2.wav", NSHomeDirectory() + "/Desktop/Virtual_Instrument/AudioFiles/F4 - Pad2.wav"]
    
    let Gb = [NSHomeDirectory() + "/Desktop/Virtual_Instrument/AudioFiles/Gb1.wav", NSHomeDirectory() + "/Desktop/Virtual_Instrument/AudioFiles/Gb2.wav", NSHomeDirectory() + "/Desktop/Virtual_Instrument/AudioFiles/Gb3.wav", NSHomeDirectory() + "/Desktop/Virtual_Instrument/AudioFiles/Gb4.wav", NSHomeDirectory() + "/Desktop/Virtual_Instrument/AudioFiles/F#1 - Strings.wav", NSHomeDirectory() + "/Desktop/Virtual_Instrument/AudioFiles/F#2 - Strings.wav", NSHomeDirectory() + "/Desktop/Virtual_Instrument/AudioFiles/F#3 - Strings.wav", NSHomeDirectory() + "/Desktop/Virtual_Instrument/AudioFiles/F#4 - Strings.wav", NSHomeDirectory() + "/Desktop/Virtual_Instrument/AudioFiles/F#1 - Horns.wav", NSHomeDirectory() + "/Desktop/Virtual_Instrument/AudioFiles/F#2 - Horns.wav", NSHomeDirectory() + "/Desktop/Virtual_Instrument/AudioFiles/F#3 - Horns.wav", NSHomeDirectory() + "/Desktop/Virtual_Instrument/AudioFiles/F#4 - Horns.wav", NSHomeDirectory() + "/Desktop/Virtual_Instrument/AudioFiles/F#1 - Synth1.wav", NSHomeDirectory() + "/Desktop/Virtual_Instrument/AudioFiles/F#2 - Synth1.wav", NSHomeDirectory() + "/Desktop/Virtual_Instrument/AudioFiles/F#3 - Synth1.wav", NSHomeDirectory() + "/Desktop/Virtual_Instrument/AudioFiles/F#4 - Synth1.wav", NSHomeDirectory() + "/Desktop/Virtual_Instrument/AudioFiles/F#1 - Synth2.wav", NSHomeDirectory() + "/Desktop/Virtual_Instrument/AudioFiles/F#2 - Synth2.wav", NSHomeDirectory() + "/Desktop/Virtual_Instrument/AudioFiles/F#3 - Synth2.wav", NSHomeDirectory() + "/Desktop/Virtual_Instrument/AudioFiles/F#4 - Synth2.wav", NSHomeDirectory() + "/Desktop/Virtual_Instrument/AudioFiles/F#1 - Pad1.wav", NSHomeDirectory() + "/Desktop/Virtual_Instrument/AudioFiles/F#2 - Pad1.wav", NSHomeDirectory() + "/Desktop/Virtual_Instrument/AudioFiles/F#3 - Pad1.wav", NSHomeDirectory() + "/Desktop/Virtual_Instrument/AudioFiles/F#4 - Pad1.wav", NSHomeDirectory() + "/Desktop/Virtual_Instrument/AudioFiles/F#1 - Pad2.wav", NSHomeDirectory() + "/Desktop/Virtual_Instrument/AudioFiles/F#2 - Pad2.wav", NSHomeDirectory() + "/Desktop/Virtual_Instrument/AudioFiles/F#3 - Pad2.wav", NSHomeDirectory() + "/Desktop/Virtual_Instrument/AudioFiles/F#4 - Pad2.wav"]
    
    let G = [NSHomeDirectory() + "/Desktop/Virtual_Instrument/AudioFiles/G1.wav", NSHomeDirectory() + "/Desktop/Virtual_Instrument/AudioFiles/G2.wav", NSHomeDirectory() + "/Desktop/Virtual_Instrument/AudioFiles/G3.wav", NSHomeDirectory() + "/Desktop/Virtual_Instrument/AudioFiles/G4.wav", NSHomeDirectory() + "/Desktop/Virtual_Instrument/AudioFiles/G1 - Strings.wav", NSHomeDirectory() + "/Desktop/Virtual_Instrument/AudioFiles/G2 - Strings.wav", NSHomeDirectory() + "/Desktop/Virtual_Instrument/AudioFiles/G3 - Strings.wav", NSHomeDirectory() + "/Desktop/Virtual_Instrument/AudioFiles/G4 - Strings.wav", NSHomeDirectory() + "/Desktop/Virtual_Instrument/AudioFiles/G1 - Horns.wav", NSHomeDirectory() + "/Desktop/Virtual_Instrument/AudioFiles/G2 - Horns.wav", NSHomeDirectory() + "/Desktop/Virtual_Instrument/AudioFiles/G3 - Horns.wav", NSHomeDirectory() + "/Desktop/Virtual_Instrument/AudioFiles/G4 - Horns.wav", NSHomeDirectory() + "/Desktop/Virtual_Instrument/AudioFiles/G1 - Synth1.wav", NSHomeDirectory() + "/Desktop/Virtual_Instrument/AudioFiles/G2 - Synth1.wav", NSHomeDirectory() + "/Desktop/Virtual_Instrument/AudioFiles/G3 - Synth1.wav", NSHomeDirectory() + "/Desktop/Virtual_Instrument/AudioFiles/G4 - Synth1.wav", NSHomeDirectory() + "/Desktop/Virtual_Instrument/AudioFiles/G1 - Synth2.wav", NSHomeDirectory() + "/Desktop/Virtual_Instrument/AudioFiles/G2 - Synth2.wav", NSHomeDirectory() + "/Desktop/Virtual_Instrument/AudioFiles/G3 - Synth2.wav", NSHomeDirectory() + "/Desktop/Virtual_Instrument/AudioFiles/G4 - Synth2.wav", NSHomeDirectory() + "/Desktop/Virtual_Instrument/AudioFiles/G1 - Pad1.wav", NSHomeDirectory() + "/Desktop/Virtual_Instrument/AudioFiles/G2 - Pad1.wav", NSHomeDirectory() + "/Desktop/Virtual_Instrument/AudioFiles/G3 - Pad1.wav", NSHomeDirectory() + "/Desktop/Virtual_Instrument/AudioFiles/G4 - Pad1.wav", NSHomeDirectory() + "/Desktop/Virtual_Instrument/AudioFiles/G1 - Pad2.wav", NSHomeDirectory() + "/Desktop/Virtual_Instrument/AudioFiles/G2 - Pad2.wav", NSHomeDirectory() + "/Desktop/Virtual_Instrument/AudioFiles/G3 - Pad2.wav", NSHomeDirectory() + "/Desktop/Virtual_Instrument/AudioFiles/G4 - Pad2.wav"]
    
    let Ab = [NSHomeDirectory() + "/Desktop/Virtual_Instrument/AudioFiles/Ab1.wav", NSHomeDirectory() + "/Desktop/Virtual_Instrument/AudioFiles/Ab2.wav", NSHomeDirectory() + "/Desktop/Virtual_Instrument/AudioFiles/Ab3.wav", NSHomeDirectory() + "/Desktop/Virtual_Instrument/AudioFiles/Ab4.wav", NSHomeDirectory() + "/Desktop/Virtual_Instrument/AudioFiles/G#1 - Strings.wav", NSHomeDirectory() + "/Desktop/Virtual_Instrument/AudioFiles/G#2 - Strings.wav", NSHomeDirectory() + "/Desktop/Virtual_Instrument/AudioFiles/G#3 - Strings.wav", NSHomeDirectory() + "/Desktop/Virtual_Instrument/AudioFiles/G#4 - Strings.wav", NSHomeDirectory() + "/Desktop/Virtual_Instrument/AudioFiles/G#1 - Horns.wav", NSHomeDirectory() + "/Desktop/Virtual_Instrument/AudioFiles/G#2 - Horns.wav", NSHomeDirectory() + "/Desktop/Virtual_Instrument/AudioFiles/G#3 - Horns.wav", NSHomeDirectory() + "/Desktop/Virtual_Instrument/AudioFiles/G#4 - Horns.wav", NSHomeDirectory() + "/Desktop/Virtual_Instrument/AudioFiles/G#1 - Synth1.wav", NSHomeDirectory() + "/Desktop/Virtual_Instrument/AudioFiles/G#2 - Synth1.wav", NSHomeDirectory() + "/Desktop/Virtual_Instrument/AudioFiles/G#3 - Synth1.wav", NSHomeDirectory() + "/Desktop/Virtual_Instrument/AudioFiles/G#4 - Synth1.wav", NSHomeDirectory() + "/Desktop/Virtual_Instrument/AudioFiles/G#1 - Synth2.wav", NSHomeDirectory() + "/Desktop/Virtual_Instrument/AudioFiles/G#2 - Synth2.wav", NSHomeDirectory() + "/Desktop/Virtual_Instrument/AudioFiles/G#3 - Synth2.wav", NSHomeDirectory() + "/Desktop/Virtual_Instrument/AudioFiles/G#4 - Synth2.wav", NSHomeDirectory() + "/Desktop/Virtual_Instrument/AudioFiles/G#1 - Pad1.wav", NSHomeDirectory() + "/Desktop/Virtual_Instrument/AudioFiles/G#2 - Pad1.wav", NSHomeDirectory() + "/Desktop/Virtual_Instrument/AudioFiles/G#3 - Pad1.wav", NSHomeDirectory() + "/Desktop/Virtual_Instrument/AudioFiles/G#4 - Pad1.wav", NSHomeDirectory() + "/Desktop/Virtual_Instrument/AudioFiles/G#1 - Pad2.wav", NSHomeDirectory() + "/Desktop/Virtual_Instrument/AudioFiles/G#2 - Pad2.wav", NSHomeDirectory() + "/Desktop/Virtual_Instrument/AudioFiles/G#3 - Pad2.wav", NSHomeDirectory() + "/Desktop/Virtual_Instrument/AudioFiles/G#4 - Pad2.wav"]
    
    let A = [NSHomeDirectory() + "/Desktop/Virtual_Instrument/AudioFiles/A1.wav", NSHomeDirectory() + "/Desktop/Virtual_Instrument/AudioFiles/A2.wav", NSHomeDirectory() + "/Desktop/Virtual_Instrument/AudioFiles/A3.wav", NSHomeDirectory() + "/Desktop/Virtual_Instrument/AudioFiles/A4.wav", NSHomeDirectory() + "/Desktop/Virtual_Instrument/AudioFiles/A1 - Strings.wav", NSHomeDirectory() + "/Desktop/Virtual_Instrument/AudioFiles/A2 - Strings.wav", NSHomeDirectory() + "/Desktop/Virtual_Instrument/AudioFiles/A3 - Strings.wav", NSHomeDirectory() + "/Desktop/Virtual_Instrument/AudioFiles/A4 - Strings.wav", NSHomeDirectory() + "/Desktop/Virtual_Instrument/AudioFiles/A1 - Horns.wav", NSHomeDirectory() + "/Desktop/Virtual_Instrument/AudioFiles/A2 - Horns.wav", NSHomeDirectory() + "/Desktop/Virtual_Instrument/AudioFiles/A3 - Horns.wav", NSHomeDirectory() + "/Desktop/Virtual_Instrument/AudioFiles/A4 - Horns.wav", NSHomeDirectory() + "/Desktop/Virtual_Instrument/AudioFiles/A1 - Synth1.wav", NSHomeDirectory() + "/Desktop/Virtual_Instrument/AudioFiles/A2 - Synth1.wav", NSHomeDirectory() + "/Desktop/Virtual_Instrument/AudioFiles/A3 - Synth1.wav", NSHomeDirectory() + "/Desktop/Virtual_Instrument/AudioFiles/A4 - Synth1.wav", NSHomeDirectory() + "/Desktop/Virtual_Instrument/AudioFiles/A1 - Synth2.wav", NSHomeDirectory() + "/Desktop/Virtual_Instrument/AudioFiles/A2 - Synth2.wav", NSHomeDirectory() + "/Desktop/Virtual_Instrument/AudioFiles/A3 - Synth2.wav", NSHomeDirectory() + "/Desktop/Virtual_Instrument/AudioFiles/A4 - Synth2.wav", NSHomeDirectory() + "/Desktop/Virtual_Instrument/AudioFiles/A1 - Pad1.wav", NSHomeDirectory() + "/Desktop/Virtual_Instrument/AudioFiles/A2 - Pad1.wav", NSHomeDirectory() + "/Desktop/Virtual_Instrument/AudioFiles/A3 - Pad1.wav", NSHomeDirectory() + "/Desktop/Virtual_Instrument/AudioFiles/A4 - Pad1.wav", NSHomeDirectory() + "/Desktop/Virtual_Instrument/AudioFiles/A1 - Pad2.wav", NSHomeDirectory() + "/Desktop/Virtual_Instrument/AudioFiles/A2 - Pad2.wav", NSHomeDirectory() + "/Desktop/Virtual_Instrument/AudioFiles/A3 - Pad2.wav", NSHomeDirectory() + "/Desktop/Virtual_Instrument/AudioFiles/A4 - Pad2.wav"]
    
    let Bb = [NSHomeDirectory() + "/Desktop/Virtual_Instrument/AudioFiles/Bb1.wav", NSHomeDirectory() + "/Desktop/Virtual_Instrument/AudioFiles/Bb2.wav", NSHomeDirectory() + "/Desktop/Virtual_Instrument/AudioFiles/Bb3.wav", NSHomeDirectory() + "/Desktop/Virtual_Instrument/AudioFiles/Bb4.wav", NSHomeDirectory() + "/Desktop/Virtual_Instrument/AudioFiles/A#1 - Strings.wav", NSHomeDirectory() + "/Desktop/Virtual_Instrument/AudioFiles/A#2 - Strings.wav", NSHomeDirectory() + "/Desktop/Virtual_Instrument/AudioFiles/A#3 - Strings.wav", NSHomeDirectory() + "/Desktop/Virtual_Instrument/AudioFiles/A#4 - Strings.wav", NSHomeDirectory() + "/Desktop/Virtual_Instrument/AudioFiles/A#1 - Horns.wav", NSHomeDirectory() + "/Desktop/Virtual_Instrument/AudioFiles/A#2 - Horns.wav", NSHomeDirectory() + "/Desktop/Virtual_Instrument/AudioFiles/A#3 - Horns.wav", NSHomeDirectory() + "/Desktop/Virtual_Instrument/AudioFiles/A#4 - Horns.wav", NSHomeDirectory() + "/Desktop/Virtual_Instrument/AudioFiles/A#1 - Synth1.wav", NSHomeDirectory() + "/Desktop/Virtual_Instrument/AudioFiles/A#2 - Synth1.wav", NSHomeDirectory() + "/Desktop/Virtual_Instrument/AudioFiles/A#3 - Synth1.wav", NSHomeDirectory() + "/Desktop/Virtual_Instrument/AudioFiles/A#4 - Synth1.wav", NSHomeDirectory() + "/Desktop/Virtual_Instrument/AudioFiles/A#1 - Synth2.wav", NSHomeDirectory() + "/Desktop/Virtual_Instrument/AudioFiles/A#2 - Synth2.wav", NSHomeDirectory() + "/Desktop/Virtual_Instrument/AudioFiles/A#3 - Synth2.wav", NSHomeDirectory() + "/Desktop/Virtual_Instrument/AudioFiles/A#4 - Synth2.wav", NSHomeDirectory() + "/Desktop/Virtual_Instrument/AudioFiles/A#1 - Pad1.wav", NSHomeDirectory() + "/Desktop/Virtual_Instrument/AudioFiles/A#2 - Pad1.wav", NSHomeDirectory() + "/Desktop/Virtual_Instrument/AudioFiles/A#3 - Pad1.wav", NSHomeDirectory() + "/Desktop/Virtual_Instrument/AudioFiles/A#4 - Pad1.wav", NSHomeDirectory() + "/Desktop/Virtual_Instrument/AudioFiles/A#1 - Pad2.wav", NSHomeDirectory() + "/Desktop/Virtual_Instrument/AudioFiles/A#2 - Pad2.wav", NSHomeDirectory() + "/Desktop/Virtual_Instrument/AudioFiles/A#3 - Pad2.wav", NSHomeDirectory() + "/Desktop/Virtual_Instrument/AudioFiles/A#4 - Pad2.wav"]
    
    let B = [NSHomeDirectory() + "/Desktop/Virtual_Instrument/AudioFiles/B1.wav", NSHomeDirectory() + "/Desktop/Virtual_Instrument/AudioFiles/B2.wav", NSHomeDirectory() + "/Desktop/Virtual_Instrument/AudioFiles/B3.wav", NSHomeDirectory() + "/Desktop/Virtual_Instrument/AudioFiles/B4.wav", NSHomeDirectory() + "/Desktop/Virtual_Instrument/AudioFiles/B1 - Strings.wav", NSHomeDirectory() + "/Desktop/Virtual_Instrument/AudioFiles/B2 - Strings.wav", NSHomeDirectory() + "/Desktop/Virtual_Instrument/AudioFiles/B3 - Strings.wav", NSHomeDirectory() + "/Desktop/Virtual_Instrument/AudioFiles/B4 - Strings.wav",  NSHomeDirectory() + "/Desktop/Virtual_Instrument/AudioFiles/B1 - Horns.wav", NSHomeDirectory() + "/Desktop/Virtual_Instrument/AudioFiles/B2 - Horns.wav", NSHomeDirectory() + "/Desktop/Virtual_Instrument/AudioFiles/B3 - Horns.wav", NSHomeDirectory() + "/Desktop/Virtual_Instrument/AudioFiles/B4 - Horns.wav", NSHomeDirectory() + "/Desktop/Virtual_Instrument/AudioFiles/B1 - Synth1.wav", NSHomeDirectory() + "/Desktop/Virtual_Instrument/AudioFiles/B2 - Synth1.wav", NSHomeDirectory() + "/Desktop/Virtual_Instrument/AudioFiles/B3 - Synth1.wav", NSHomeDirectory() + "/Desktop/Virtual_Instrument/AudioFiles/B4 - Synth1.wav", NSHomeDirectory() + "/Desktop/Virtual_Instrument/AudioFiles/B1 - Synth2.wav", NSHomeDirectory() + "/Desktop/Virtual_Instrument/AudioFiles/B2 - Synth2.wav", NSHomeDirectory() + "/Desktop/Virtual_Instrument/AudioFiles/B3 - Synth2.wav", NSHomeDirectory() + "/Desktop/Virtual_Instrument/AudioFiles/B4 - Synth2.wav", NSHomeDirectory() + "/Desktop/Virtual_Instrument/AudioFiles/B1 - Pad1.wav", NSHomeDirectory() + "/Desktop/Virtual_Instrument/AudioFiles/B2 - Pad1.wav", NSHomeDirectory() + "/Desktop/Virtual_Instrument/AudioFiles/B3 - Pad1.wav", NSHomeDirectory() + "/Desktop/Virtual_Instrument/AudioFiles/B4 - Pad1.wav", NSHomeDirectory() + "/Desktop/Virtual_Instrument/AudioFiles/B1 - Pad2.wav", NSHomeDirectory() + "/Desktop/Virtual_Instrument/AudioFiles/B2 - Pad2.wav", NSHomeDirectory() + "/Desktop/Virtual_Instrument/AudioFiles/B3 - Pad2.wav", NSHomeDirectory() + "/Desktop/Virtual_Instrument/AudioFiles/B4 - Pad2.wav"]
    
    
    let outLocation = NSHomeDirectory() + "/Desktop/Virtual_Instrument/Recordings/out.wav"
    
}
